# Generated by Django 4.0 on 2021-12-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputmodel',
            options={'verbose_name': 'Name', 'verbose_name_plural': 'Names'},
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='field',
            field=models.CharField(max_length=50),
        ),
    ]
